/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_danielagurcia;

/**
 *
 * @author Daniel Agurcia
 */
public class Manejador_Empresas extends javax.swing.JFrame {

    /**
     * Creates new form Manejador_Empresas
     */
    public Manejador_Empresas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_principal = new javax.swing.JDialog();
        jl_nombre_empresa = new javax.swing.JLabel();
        jl_id_empresa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_empresas = new javax.swing.JTree();
        jb_crear_empleado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_lista_empleados = new javax.swing.JList<>();
        jb_logout = new javax.swing.JButton();
        jd_crear_empresa = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nombre_empresa = new javax.swing.JTextField();
        jd_fechafundacion_empresa = new com.toedter.calendar.JDateChooser();
        cb_capital_financiero = new javax.swing.JComboBox<>();
        tf_ubicacion_sucursal = new javax.swing.JTextField();
        tf_id_sucursal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pf_pin_acceso = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jd_crear_usuario = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_nombre_empleado = new javax.swing.JTextField();
        jd_fechanacimiento_empleado = new com.toedter.calendar.JDateChooser();
        tf_correo_empleado = new javax.swing.JTextField();
        cb_Cargo_empleado = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jb_ingresar_empleado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_id_acceso = new javax.swing.JTextField();
        pf_pin_acceso_principal = new javax.swing.JPasswordField();
        jb_crear_empresa = new javax.swing.JButton();
        jb_entrar = new javax.swing.JButton();

        jl_nombre_empresa.setText("jLabel4");

        jl_id_empresa.setText("jLabel5");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jt_empresas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jt_empresas);

        jb_crear_empleado.setText("Crear Empleado");

        jScrollPane2.setViewportView(jl_lista_empleados);

        jb_logout.setText("Logout");

        javax.swing.GroupLayout jd_principalLayout = new javax.swing.GroupLayout(jd_principal.getContentPane());
        jd_principal.getContentPane().setLayout(jd_principalLayout);
        jd_principalLayout.setHorizontalGroup(
            jd_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_principalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jd_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_principalLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jd_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_principalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_principalLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jb_crear_empleado)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jd_principalLayout.createSequentialGroup()
                        .addComponent(jl_nombre_empresa)
                        .addGap(265, 265, 265)
                        .addComponent(jl_id_empresa)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jd_principalLayout.setVerticalGroup(
            jd_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_principalLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jd_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombre_empresa)
                    .addComponent(jl_id_empresa))
                .addGap(9, 9, 9)
                .addGroup(jd_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_principalLayout.createSequentialGroup()
                        .addGap(0, 91, Short.MAX_VALUE)
                        .addComponent(jb_crear_empleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_logout, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        jLabel6.setText("Nombre de la Empresa");

        jLabel7.setText("Capital Financiero");

        jLabel8.setText("Fecha Fundacion");

        jLabel9.setText("Ubicacion de la Sucursal");

        jLabel10.setText("ID de la Sucursal");

        cb_capital_financiero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tf_id_sucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_id_sucursalActionPerformed(evt);
            }
        });

        jLabel11.setText("Pin de Acceso");

        jLabel12.setText("Crear Empresa");

        javax.swing.GroupLayout jd_crear_empresaLayout = new javax.swing.GroupLayout(jd_crear_empresa.getContentPane());
        jd_crear_empresa.getContentPane().setLayout(jd_crear_empresaLayout);
        jd_crear_empresaLayout.setHorizontalGroup(
            jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_empresaLayout.createSequentialGroup()
                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crear_empresaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jd_crear_empresaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(54, 54, 54)
                                .addComponent(tf_nombre_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crear_empresaLayout.createSequentialGroup()
                                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jd_crear_empresaLayout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(34, 34, 34))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)))
                                    .addComponent(jLabel11))
                                .addGap(12, 12, 12)
                                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cb_capital_financiero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jd_fechafundacion_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tf_ubicacion_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(pf_pin_acceso, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_id_sucursal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jd_crear_empresaLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel12)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jd_crear_empresaLayout.setVerticalGroup(
            jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_empresaLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_nombre_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb_capital_financiero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jd_fechafundacion_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_ubicacion_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_id_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pf_pin_acceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        jLabel13.setText("Nombre Completo");

        jLabel14.setText("Fecha de Nacimiento");

        jLabel15.setText("Correo Electronico");

        jLabel16.setText("Cargo");

        cb_Cargo_empleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniero", "Medico", "Estudiante", "Licenciado", "Maestro" }));

        jLabel17.setText("Crear Empleado");

        jb_ingresar_empleado.setText("Crear Empleado");

        javax.swing.GroupLayout jd_crear_usuarioLayout = new javax.swing.GroupLayout(jd_crear_usuario.getContentPane());
        jd_crear_usuario.getContentPane().setLayout(jd_crear_usuarioLayout);
        jd_crear_usuarioLayout.setHorizontalGroup(
            jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(tf_nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jd_fechanacimiento_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cb_Cargo_empleado, 0, 141, Short.MAX_VALUE)
                                            .addComponent(tf_correo_empleado)))))
                            .addComponent(jLabel15)))
                    .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel17))
                    .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jb_ingresar_empleado)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jd_crear_usuarioLayout.setVerticalGroup(
            jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                        .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tf_nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel14))
                    .addComponent(jd_fechanacimiento_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_correo_empleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cb_Cargo_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_ingresar_empleado)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido");

        jLabel2.setText("ID de la Empresa");

        jLabel3.setText("Pin de Acceso");

        jb_crear_empresa.setText("Crear Empresa");

        jb_entrar.setText("Entrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_entrar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pf_pin_acceso_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                            .addComponent(tf_id_acceso))
                                        .addGap(18, 18, 18)
                                        .addComponent(jb_crear_empresa))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_id_acceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_crear_empresa))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pf_pin_acceso_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_entrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_id_sucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_id_sucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_id_sucursalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manejador_Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manejador_Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manejador_Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manejador_Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manejador_Empresas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_Cargo_empleado;
    private javax.swing.JComboBox<String> cb_capital_financiero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_crear_empleado;
    private javax.swing.JButton jb_crear_empresa;
    private javax.swing.JButton jb_entrar;
    private javax.swing.JButton jb_ingresar_empleado;
    private javax.swing.JButton jb_logout;
    private javax.swing.JDialog jd_crear_empresa;
    private javax.swing.JDialog jd_crear_usuario;
    private com.toedter.calendar.JDateChooser jd_fechafundacion_empresa;
    private com.toedter.calendar.JDateChooser jd_fechanacimiento_empleado;
    private javax.swing.JDialog jd_principal;
    private javax.swing.JLabel jl_id_empresa;
    private javax.swing.JList<String> jl_lista_empleados;
    private javax.swing.JLabel jl_nombre_empresa;
    private javax.swing.JTree jt_empresas;
    private javax.swing.JPasswordField pf_pin_acceso;
    private javax.swing.JPasswordField pf_pin_acceso_principal;
    private javax.swing.JTextField tf_correo_empleado;
    private javax.swing.JTextField tf_id_acceso;
    private javax.swing.JTextField tf_id_sucursal;
    private javax.swing.JTextField tf_nombre_empleado;
    private javax.swing.JTextField tf_nombre_empresa;
    private javax.swing.JTextField tf_ubicacion_sucursal;
    // End of variables declaration//GEN-END:variables
}
