/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_danielagurcia;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Daniel Agurcia
 */
public class Manejador_Empresas extends javax.swing.JFrame {

    /**
     * Creates new form Manejador_Empresas
     */
    public Manejador_Empresas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_principal = new javax.swing.JDialog();
        jl_nombre_empresa = new javax.swing.JLabel();
        jl_id_empresa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_empresas = new javax.swing.JTree();
        jb_crear_empleado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_lista_empleados = new javax.swing.JList<>();
        jb_logout = new javax.swing.JButton();
        jd_crear_empresa = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nombre_empresa = new javax.swing.JTextField();
        jd_fechafundacion_empresa = new com.toedter.calendar.JDateChooser();
        cb_capital_financiero = new javax.swing.JComboBox<>();
        tf_ubicacion_sucursal = new javax.swing.JTextField();
        tf_id_sucursal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pf_pin_acceso = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jb_crearempresa = new javax.swing.JButton();
        jd_crear_usuario = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_nombre_empleado = new javax.swing.JTextField();
        jd_fechanacimiento_empleado = new com.toedter.calendar.JDateChooser();
        tf_correo_empleado = new javax.swing.JTextField();
        cb_Cargo_empleado = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jb_ingresar_empleado = new javax.swing.JButton();
        popup = new javax.swing.JPopupMenu();
        jmi_modificar = new javax.swing.JMenuItem();
        jmi_eliminar = new javax.swing.JMenuItem();
        jmi_ver_detalles = new javax.swing.JMenuItem();
        jmi_contratar = new javax.swing.JMenuItem();
        jd_modificar = new javax.swing.JDialog();
        cb_Cargo_empleado1 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jb_ingresar_empleado1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tf_nombre_empleado1 = new javax.swing.JTextField();
        jd_fechanacimiento_empleado1 = new com.toedter.calendar.JDateChooser();
        tf_correo_empleado1 = new javax.swing.JTextField();
        popup_arbol = new javax.swing.JPopupMenu();
        jmi_detalles_arbol = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_id_acceso = new javax.swing.JTextField();
        pf_pin_acceso_principal = new javax.swing.JPasswordField();
        jb_crear_empresa = new javax.swing.JButton();
        jb_entrar = new javax.swing.JButton();

        jl_nombre_empresa.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jl_nombre_empresa.setText("jLabel4");

        jl_id_empresa.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jl_id_empresa.setText("jLabel5");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Empresas");
        jt_empresas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_empresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_empresasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_empresas);

        jb_crear_empleado.setText("Crear Empleado");
        jb_crear_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crear_empleadoMouseClicked(evt);
            }
        });

        jl_lista_empleados.setModel(new DefaultListModel());
        jl_lista_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_lista_empleadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_lista_empleados);

        jb_logout.setText("Logout");
        jb_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_principalLayout = new javax.swing.GroupLayout(jd_principal.getContentPane());
        jd_principal.getContentPane().setLayout(jd_principalLayout);
        jd_principalLayout.setHorizontalGroup(
            jd_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_principalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jd_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_principalLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jd_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_principalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_principalLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jb_crear_empleado)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jd_principalLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jl_nombre_empresa)
                        .addGap(224, 224, 224)
                        .addComponent(jl_id_empresa)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jd_principalLayout.setVerticalGroup(
            jd_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_principalLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jd_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombre_empresa)
                    .addComponent(jl_id_empresa))
                .addGap(9, 9, 9)
                .addGroup(jd_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_principalLayout.createSequentialGroup()
                        .addGap(0, 75, Short.MAX_VALUE)
                        .addComponent(jb_crear_empleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_logout, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        jLabel6.setText("Nombre de la Empresa");

        jLabel7.setText("Capital Financiero");

        jLabel8.setText("Fecha Fundacion");

        jLabel9.setText("Ubicacion de la Sucursal");

        jLabel10.setText("ID de la Sucursal");

        cb_capital_financiero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "80000", "120000", "169000" }));

        tf_id_sucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_id_sucursalActionPerformed(evt);
            }
        });

        jLabel11.setText("Pin de Acceso");

        jLabel12.setText("Crear Empresa");

        jb_crearempresa.setText("Crear");
        jb_crearempresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearempresaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crear_empresaLayout = new javax.swing.GroupLayout(jd_crear_empresa.getContentPane());
        jd_crear_empresa.getContentPane().setLayout(jd_crear_empresaLayout);
        jd_crear_empresaLayout.setHorizontalGroup(
            jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_empresaLayout.createSequentialGroup()
                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crear_empresaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jd_crear_empresaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(54, 54, 54)
                                .addComponent(tf_nombre_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crear_empresaLayout.createSequentialGroup()
                                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jd_crear_empresaLayout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(34, 34, 34))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)))
                                    .addComponent(jLabel11))
                                .addGap(12, 12, 12)
                                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cb_capital_financiero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jd_fechafundacion_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tf_ubicacion_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(pf_pin_acceso, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_id_sucursal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jd_crear_empresaLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel12))
                    .addGroup(jd_crear_empresaLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jb_crearempresa)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jd_crear_empresaLayout.setVerticalGroup(
            jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_empresaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_nombre_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb_capital_financiero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jd_fechafundacion_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_ubicacion_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_id_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crear_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pf_pin_acceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_crearempresa)
                .addGap(8, 8, 8))
        );

        jLabel13.setText("Nombre Completo");

        jLabel14.setText("Fecha de Nacimiento");

        jLabel15.setText("Correo Electronico");

        jLabel16.setText("Cargo");

        cb_Cargo_empleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniero", "Medico", "Estudiante", "Licenciado", "Maestro" }));

        jLabel17.setText("Crear Empleado");

        jb_ingresar_empleado.setText("Crear Empleado");
        jb_ingresar_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ingresar_empleadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crear_usuarioLayout = new javax.swing.GroupLayout(jd_crear_usuario.getContentPane());
        jd_crear_usuario.getContentPane().setLayout(jd_crear_usuarioLayout);
        jd_crear_usuarioLayout.setHorizontalGroup(
            jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(tf_nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jd_fechanacimiento_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cb_Cargo_empleado, 0, 141, Short.MAX_VALUE)
                                            .addComponent(tf_correo_empleado)))))
                            .addComponent(jLabel15)))
                    .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel17))
                    .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jb_ingresar_empleado)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jd_crear_usuarioLayout.setVerticalGroup(
            jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_crear_usuarioLayout.createSequentialGroup()
                        .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tf_nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel14))
                    .addComponent(jd_fechanacimiento_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_correo_empleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jd_crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cb_Cargo_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_ingresar_empleado)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jmi_modificar.setText("Modificar");
        jmi_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modificarActionPerformed(evt);
            }
        });
        popup.add(jmi_modificar);

        jmi_eliminar.setText("Eliminar");
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        popup.add(jmi_eliminar);

        jmi_ver_detalles.setText("Ver Detalles");
        jmi_ver_detalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ver_detallesActionPerformed(evt);
            }
        });
        popup.add(jmi_ver_detalles);

        jmi_contratar.setText("Contratar");
        jmi_contratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_contratarActionPerformed(evt);
            }
        });
        popup.add(jmi_contratar);

        cb_Cargo_empleado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniero", "Medico", "Estudiante", "Licenciado", "Maestro" }));

        jLabel18.setText("Modificar Empleado");

        jLabel19.setText("Nombre Completo");

        jb_ingresar_empleado1.setText("Modificar Empleado");
        jb_ingresar_empleado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ingresar_empleado1MouseClicked(evt);
            }
        });

        jLabel20.setText("Fecha de Nacimiento");

        jLabel21.setText("Correo Electronico");

        jLabel22.setText("Cargo");

        javax.swing.GroupLayout jd_modificarLayout = new javax.swing.GroupLayout(jd_modificar.getContentPane());
        jd_modificar.getContentPane().setLayout(jd_modificarLayout);
        jd_modificarLayout.setHorizontalGroup(
            jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarLayout.createSequentialGroup()
                .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificarLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(jd_modificarLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(tf_nombre_empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_modificarLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_modificarLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jd_fechanacimiento_empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_modificarLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cb_Cargo_empleado1, 0, 141, Short.MAX_VALUE)
                                            .addComponent(tf_correo_empleado1)))))
                            .addComponent(jLabel21)))
                    .addGroup(jd_modificarLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel18))
                    .addGroup(jd_modificarLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jb_ingresar_empleado1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_modificarLayout.setVerticalGroup(
            jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_modificarLayout.createSequentialGroup()
                        .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(tf_nombre_empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel20))
                    .addComponent(jd_fechanacimiento_empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_correo_empleado1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cb_Cargo_empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_ingresar_empleado1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jmi_detalles_arbol.setText("Ver Detalles");
        jmi_detalles_arbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_detalles_arbolActionPerformed(evt);
            }
        });
        popup_arbol.add(jmi_detalles_arbol);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido");

        jLabel2.setText("ID de la Empresa");

        jLabel3.setText("Pin de Acceso");

        jb_crear_empresa.setText("Crear Empresa");
        jb_crear_empresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crear_empresaMouseClicked(evt);
            }
        });

        jb_entrar.setText("Entrar");
        jb_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_entrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_entrar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pf_pin_acceso_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                            .addComponent(tf_id_acceso))
                                        .addGap(18, 18, 18)
                                        .addComponent(jb_crear_empresa))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_id_acceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_crear_empresa))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pf_pin_acceso_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_entrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_id_sucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_id_sucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_id_sucursalActionPerformed

    private void jb_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_entrarActionPerformed
        boolean acceso = false;
        try {
            int id = Integer.parseInt(tf_id_acceso.getText());
            String password = pf_pin_acceso_principal.getText();
            for (Empresa temp : lista_empresas) {
                if (temp.getId_sucursal() == id && temp.getPin_acceso().equals(password)) {
                    acceso = true;
                    empresa_ingresada = temp;
                }
            }
            if (acceso == true) {
                jl_nombre_empresa.setText(empresa_ingresada.getNombre());
                jl_id_empresa.setText("ID: " + String.valueOf(empresa_ingresada.getId_sucursal()));
                DefaultTreeModel modelo_arbol = (DefaultTreeModel) jt_empresas.getModel();
                DefaultMutableTreeNode nombre = new DefaultMutableTreeNode(new DefaultMutableTreeNode(empresa_ingresada.getNombre()));
                modelo_arbol.setRoot(nombre);
                DefaultMutableTreeNode nodo_empresa = (DefaultMutableTreeNode) modelo_arbol.getRoot();
                for (Empleado temp : empresa_ingresada.getLista_empleados()) {
                    DefaultMutableTreeNode nodo_empleado = new DefaultMutableTreeNode(temp);
                    for (Empleado temp2 : temp.getLista_contratados()) {
                        DefaultMutableTreeNode nodo_contratado = new DefaultMutableTreeNode(temp2);
                        nodo_empleado.add(nodo_contratado);
                    }
                    nodo_empresa.add(nodo_empleado);
                }
                modelo_arbol.reload();
                jd_principal.pack();
                jd_principal.setModal(true);
                jd_principal.setLocationRelativeTo(this);
                jd_principal.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Id o Pin Incorrecto");
            }
        } catch (Exception NumberFormatException) {
            JOptionPane.showMessageDialog(this, "Porfavor Ingrese un Id valido");
        }
    }//GEN-LAST:event_jb_entrarActionPerformed

    private void jb_crear_empresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crear_empresaMouseClicked
        jd_crear_empresa.pack();
        jd_crear_empresa.setModal(true);
        jd_crear_empresa.setLocationRelativeTo(this);
        jd_crear_empresa.setVisible(true);
    }//GEN-LAST:event_jb_crear_empresaMouseClicked

    private void jb_crearempresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearempresaMouseClicked
        try {
            String nombre = tf_nombre_empresa.getText();
            int capital = Integer.parseInt(cb_capital_financiero.getSelectedItem().toString());
            Date fecha = jd_fechafundacion_empresa.getDate();
            String ubicacion = tf_ubicacion_sucursal.getText();
            int id = Integer.parseInt(tf_id_sucursal.getText());
            String pin = pf_pin_acceso.getText();
            boolean vali_pin = false;
            for (Empresa temp : lista_empresas) {
                if (temp.getId_sucursal() == id) {
                    vali_pin = true;
                }
            }
            if (vali_pin == true) {
                JOptionPane.showMessageDialog(evt.getComponent(), "El id que ingreso ya existe, porfavor ingrese otro id");
            } else {
                Empresa x = new Empresa(nombre, capital, fecha, ubicacion, id, pin);
                lista_empresas.add(x);
                tf_nombre_empresa.setText("");
                cb_capital_financiero.setSelectedItem(0);
                jd_fechafundacion_empresa.setDate(new Date());
                tf_ubicacion_sucursal.setText("");
                tf_id_sucursal.setText("");
                pf_pin_acceso.setText("");
                JOptionPane.showMessageDialog(evt.getComponent(), "Empresa creada Exitosamente");
                jd_crear_empresa.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(evt.getComponent(), "Ocurrio un error y no se guardaron los datos");
        }

    }//GEN-LAST:event_jb_crearempresaMouseClicked

    private void jb_ingresar_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ingresar_empleadoMouseClicked
        try {
            String nombre = tf_nombre_empleado.getText();
            Date fecha = jd_fechanacimiento_empleado.getDate();
            String correo = tf_correo_empleado.getText();
            String cargo = cb_Cargo_empleado.getSelectedItem().toString();
            int salario = 0;
            switch (cargo) {
                case "Ingeniero":
                    salario = 22000;
                    break;
                case "Medico":
                    salario = 18000;
                    break;
                case "Estudiante":
                    salario = 7600;
                    break;
                case "Licenciado":
                    salario = 12000;
                    break;
                case "Maestro":
                    salario = 2000;
                    break;
                default:
                    break;
            }
            Empleado x = new Empleado(nombre, fecha, correo, cargo, salario);
            DefaultListModel modelo_lista = (DefaultListModel) jl_lista_empleados.getModel();
            modelo_lista.addElement(x);
            jl_lista_empleados.setModel(modelo_lista);
            tf_nombre_empleado.setText("");
            jd_fechanacimiento_empleado.setDate(new Date());
            tf_correo_empleado.setText("");
            cb_Cargo_empleado.setSelectedItem(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this.jd_crear_usuario, "Ocurrio un erro y no se guardaron los datos");
        }
        JOptionPane.showMessageDialog(evt.getComponent(), "Empleado Creado Exitosamente");
        jd_crear_usuario.dispose();
    }//GEN-LAST:event_jb_ingresar_empleadoMouseClicked

    private void jb_crear_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crear_empleadoMouseClicked
        jd_crear_usuario.pack();
        jd_crear_usuario.setModal(true);
        jd_crear_usuario.setLocationRelativeTo(this);
        jd_crear_usuario.setVisible(true);
    }//GEN-LAST:event_jb_crear_empleadoMouseClicked

    private void jl_lista_empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_lista_empleadosMouseClicked
        if (jl_lista_empleados.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                popup.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_lista_empleadosMouseClicked

    private void jmi_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modificarActionPerformed
        DefaultListModel modeloLista = (DefaultListModel) jl_lista_empleados.getModel();
        Empleado selec = (Empleado) modeloLista.get(jl_lista_empleados.getSelectedIndex());
        tf_correo_empleado1.setText(selec.getCorreo());
        tf_nombre_empleado1.setText(selec.getNombre());
        jd_fechanacimiento_empleado1.setDate(selec.getFecha_nacimiento());
        if (selec.getCargo().equals("Ingeniero")) {
            cb_Cargo_empleado1.setSelectedItem(0);
        } else if (selec.getCargo().equals("Medico")) {
            cb_Cargo_empleado1.setSelectedIndex(1);
        } else if (selec.getCargo().equals("Estudiante")) {
            cb_Cargo_empleado1.setSelectedIndex(2);
        } else if (selec.getCargo().equals("Licenciado")) {
            cb_Cargo_empleado1.setSelectedIndex(3);
        } else if (selec.getCargo().equals("Maestro")) {
            cb_Cargo_empleado1.setSelectedIndex(4);
        }
        jl_lista_empleados.setModel(modeloLista);
        jd_modificar.pack();
        jd_modificar.setModal(true);
        jd_modificar.setLocationRelativeTo(this);
        jd_modificar.setVisible(true);
    }//GEN-LAST:event_jmi_modificarActionPerformed

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed
        if (jl_lista_empleados.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) jl_lista_empleados.getModel();
            modelo.remove(jl_lista_empleados.getSelectedIndex());
            jl_lista_empleados.setModel(modelo);
            JOptionPane.showMessageDialog(this.jd_principal, "Eliminado Exitosamente");
        }

    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jmi_ver_detallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ver_detallesActionPerformed
        if (jl_lista_empleados.getSelectedIndex() >= 0) {
            DefaultListModel modeloLista = (DefaultListModel) jl_lista_empleados.getModel();
            Empleado selec = (Empleado) modeloLista.get(jl_lista_empleados.getSelectedIndex());
            JOptionPane.showMessageDialog(this.jd_principal, selec.toString2());
        }
    }//GEN-LAST:event_jmi_ver_detallesActionPerformed

    private void jmi_contratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_contratarActionPerformed
        if (jl_lista_empleados.getSelectedIndex() >= 0 && jt_empresas.getSelectionPath() != null) {
            if (nodo_seleccionado.equals(jl_lista_empleados.getSelectedIndex())) {
                JOptionPane.showMessageDialog(null, "No puede contratarse a si mismo");
            } else if (nodo_seleccionado.getUserObject() instanceof Empleado) {
                DefaultListModel modeloLista = (DefaultListModel) jl_lista_empleados.getModel();
                Empleado selec = (Empleado) modeloLista.get(jl_lista_empleados.getSelectedIndex());
                jl_lista_empleados.setModel(modeloLista);
                DefaultTreeModel m = (DefaultTreeModel) jt_empresas.getModel();
                DefaultMutableTreeNode nodo_raiz = (DefaultMutableTreeNode) m.getRoot();
                DefaultMutableTreeNode nodo_persona = new DefaultMutableTreeNode(selec);
                nodo_seleccionado.add(nodo_persona);
                ((Empleado) nodo_seleccionado.getUserObject()).getLista_contratados().add(selec);
                m.reload();
            } else {
                DefaultListModel modeloLista = (DefaultListModel) jl_lista_empleados.getModel();
                Empleado selec = (Empleado) modeloLista.get(jl_lista_empleados.getSelectedIndex());
                jl_lista_empleados.setModel(modeloLista);
                DefaultTreeModel m = (DefaultTreeModel) jt_empresas.getModel();
                DefaultMutableTreeNode nodo_raiz = (DefaultMutableTreeNode) m.getRoot();
                DefaultMutableTreeNode nodo_persona = new DefaultMutableTreeNode(selec);
                nodo_seleccionado.add(nodo_persona);
                empresa_ingresada.getLista_empleados().add(selec);
                m.reload();
            }
        } else {
            JOptionPane.showMessageDialog(this.jd_principal, "Porfavor seleccione una empresa para poder contratar");
        }
    }//GEN-LAST:event_jmi_contratarActionPerformed

    private void jt_empresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_empresasMouseClicked
        if (evt.isMetaDown()) {
            int row = jt_empresas.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_empresas.setSelectionRow(row);
            Object v1 = jt_empresas.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.isRoot()) {
                popup_arbol.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
        int row = jt_empresas.getClosestRowForLocation(evt.getX(), evt.getY());
        jt_empresas.setSelectionRow(row);
        Object v1 = jt_empresas.getSelectionPath().getLastPathComponent();
        nodo_seleccionado = (DefaultMutableTreeNode) v1;
    }//GEN-LAST:event_jt_empresasMouseClicked

    private void jb_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_logoutMouseClicked
        jd_principal.dispose();
    }//GEN-LAST:event_jb_logoutMouseClicked

    private void jb_ingresar_empleado1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ingresar_empleado1MouseClicked
        try {
            String nombre = tf_nombre_empleado1.getText();
            Date fecha = jd_fechanacimiento_empleado1.getDate();
            String correo = tf_correo_empleado1.getText();
            String cargo = cb_Cargo_empleado1.getSelectedItem().toString();
            int salario = 0;
            switch (cargo) {
                case "Ingeniero":
                    salario = 22000;
                    break;
                case "Medico":
                    salario = 18000;
                    break;
                case "Estudiante":
                    salario = 7600;
                    break;
                case "Licenciado":
                    salario = 12000;
                    break;
                case "Maestro":
                    salario = 2000;
                    break;
            }
            DefaultListModel modeloLista = (DefaultListModel) jl_lista_empleados.getModel();
            Empleado seleccionado = (Empleado) modeloLista.get(jl_lista_empleados.getSelectedIndex());
            seleccionado.setNombre(nombre);
            seleccionado.setFecha_nacimiento(fecha);
            seleccionado.setCorreo(correo);
            seleccionado.setCargo(cargo);
            seleccionado.setSalario(salario);
            jl_lista_empleados.setModel(modeloLista);
            tf_correo_empleado1.setText("");
            tf_nombre_empleado1.setText("");
            jd_fechanacimiento_empleado1.setDate(new Date());
            cb_Cargo_empleado1.setSelectedIndex(0);
        } catch (Exception e) {
            System.out.println("Diego al modificar me tiraba un error de array index out of bounds asaber porque, pero el codigo para modificar esta bueno");
            JOptionPane.showMessageDialog(this, "hubo un error y no se modifico");
        }
    }//GEN-LAST:event_jb_ingresar_empleado1MouseClicked

    private void jmi_detalles_arbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_detalles_arbolActionPerformed
        JOptionPane.showMessageDialog(this.jd_principal, empresa_ingresada.toString());
    }//GEN-LAST:event_jmi_detalles_arbolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manejador_Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manejador_Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manejador_Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manejador_Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manejador_Empresas().setVisible(true);
            }
        });
    }
    DefaultMutableTreeNode nodo_seleccionado;
    ArrayList<Empresa> lista_empresas = new ArrayList();
    Empresa empresa_ingresada;
    int presupuesto_empresa_ingresada;
    int contador_presupuesto = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_Cargo_empleado;
    private javax.swing.JComboBox<String> cb_Cargo_empleado1;
    private javax.swing.JComboBox<String> cb_capital_financiero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_crear_empleado;
    private javax.swing.JButton jb_crear_empresa;
    private javax.swing.JButton jb_crearempresa;
    private javax.swing.JButton jb_entrar;
    private javax.swing.JButton jb_ingresar_empleado;
    private javax.swing.JButton jb_ingresar_empleado1;
    private javax.swing.JButton jb_logout;
    private javax.swing.JDialog jd_crear_empresa;
    private javax.swing.JDialog jd_crear_usuario;
    private com.toedter.calendar.JDateChooser jd_fechafundacion_empresa;
    private com.toedter.calendar.JDateChooser jd_fechanacimiento_empleado;
    private com.toedter.calendar.JDateChooser jd_fechanacimiento_empleado1;
    private javax.swing.JDialog jd_modificar;
    private javax.swing.JDialog jd_principal;
    private javax.swing.JLabel jl_id_empresa;
    private javax.swing.JList<String> jl_lista_empleados;
    private javax.swing.JLabel jl_nombre_empresa;
    private javax.swing.JMenuItem jmi_contratar;
    private javax.swing.JMenuItem jmi_detalles_arbol;
    private javax.swing.JMenuItem jmi_eliminar;
    private javax.swing.JMenuItem jmi_modificar;
    private javax.swing.JMenuItem jmi_ver_detalles;
    private javax.swing.JTree jt_empresas;
    private javax.swing.JPasswordField pf_pin_acceso;
    private javax.swing.JPasswordField pf_pin_acceso_principal;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JPopupMenu popup_arbol;
    private javax.swing.JTextField tf_correo_empleado;
    private javax.swing.JTextField tf_correo_empleado1;
    private javax.swing.JTextField tf_id_acceso;
    private javax.swing.JTextField tf_id_sucursal;
    private javax.swing.JTextField tf_nombre_empleado;
    private javax.swing.JTextField tf_nombre_empleado1;
    private javax.swing.JTextField tf_nombre_empresa;
    private javax.swing.JTextField tf_ubicacion_sucursal;
    // End of variables declaration//GEN-END:variables
}
